### ISSUE TITLE
Getting error while syncing data 

### ISSUE THREAD

**Issue by redmont** [reservoirprotocol/reservoir-sync-node#63]
Hi,
I am running reservoir-sync-node to backfill data. I am getting this error after a while

```
/home/ubuntu/reservoir-system/reservoir-sync-node/dist/utils/index.js:50
    const datePieces = date.split('T');
                            ^

TypeError: Cannot read properties of undefined (reading 'split')
    at parseTimestamp (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/utils/index.js:50:29)
    at Worker.process (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/syncer/Worker.js:61:60)
    at Controller._launchBackup (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/syncer/Controller.js:100:24)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Any idea on how to resolve this?

**Comment by r3lays** [comment]
Hi @redmont, is this your first time running the sync node? We were seeing this issue occurred with folks who had a backup stored in redis.

Have you tried clearing the backup and restarting? 

Any way to reproduce?

**Comment by redmont** [comment]
@r3lays 
I ran it again after clearing the backups, getting the same error.

In addition to this, I am also getting this error sometimes

```
[SYNC-NODE] [20:48:25:4825] Released block: f0891192-178f-45c7-b771-dd9127355b9d

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Function.from (node:buffer:339:9)
    at toBuffer (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/utils/index.js:101:19)
    at _InsertionService._format (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/services/InsertionService.js:238:47)
    at /home/ubuntu/reservoir-system/reservoir-sync-node/dist/services/InsertionService.js:95:35
    at Array.map (<anonymous>)
    at _InsertionService.upsert (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/services/InsertionService.js:91:73)
    at _WebSocketService._insert (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/services/WebSocketService.js:153:49)
    at _WebSocketService._onMessage (/home/ubuntu/reservoir-system/reservoir-sync-node/dist/services/WebSocketService.js:132:18)
    at WebSocket.emit (node:events:513:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by r3lays** [comment]
I'll check this out and get back to you tomorrow morning.
We made some last minute additions and they might have missed some checks.

**Comment by redmont** [comment]
Hi @r3lays ,
here is the redis data before flushing
https://filebin.net/b9oxv2bxcljadons/db.1690820893767.redis

I deleted the redis backup, postgres db, checkout the branch in your latest pr `armando/grwth-3064-syncnode-v2-github-issue`
and re-ran but I got the second error again after ~45 minutes

```
[SYNC-NODE] [22:46:02:462] Grained Block
id:e11b676c-bf02-487d-afca-1022cd7ef6ad

[SYNC-NODE] [22:46:02:462] Processing Block 
id: e11b676c-bf02-487d-afca-1022cd7ef6ad

node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at toBuffer (/Users/xcx/reservoir-system/reservoir-sync-node/dist/utils/index.js:101:19)
    at _InsertionService._format (/Users/xcx/reservoir-system/reservoir-sync-node/dist/services/InsertionService.js:232:47)
    at /Users/xcx/reservoir-system/reservoir-sync-node/dist/services/InsertionService.js:95:35
    at Array.map (<anonymous>)
    at _InsertionService.upsert (/Users/xcx/reservoir-system/reservoir-sync-node/dist/services/InsertionService.js:91:73)
    at _WebSocketService._insert (/Users/xcx/reservoir-system/reservoir-sync-node/dist/services/WebSocketService.js:153:49)
    at _WebSocketService._onMessage (/Users/xcx/reservoir-system/reservoir-sync-node/dist/services/WebSocketService.js:132:18)
    at WebSocket.emit (node:events:513:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
```

**Comment by r3lays** [comment]
Hey, sorry for the late reply. Yep we got discord!
Feel free to ping me when you've joined, appreciate your patience with all this.
"relayss" - discord
https://discord.gg/SCRXu7bk - reservoir server
